### ISSUE TITLE
Review data dictionary and update variable description

### ISSUE THREAD

**Issue by mianzg** [openwashdata/boreholefuncmwi#1]
Hello @myesaya, the current data dictionary is based on your capstone project information. Please kindly review the file : https://github.com/openwashdata/boreholefuncmwi/blob/main/data-raw/dictionary.csv

Please help us to refine the dictionary by answering the following questions. Thanks!

row 5. **committee_members (integer)**
   - **Question:** Is this number of year 2023?

row 7. **annual_budget (integer)**
   - **Question:** Is the budget in Kwacha?

row 10. **tariff_costs_consider (categorical)**
      - **Question:** Can you specify this variable or list examples of costs considered?

row 13. **total_money (integer)**
    - **Question:** Is the budget in Kwacha?

row 15. **distance_materials (categorical)**
    - **Question:** How is "0-20 km" different from "within community"?

row 16. **service_provider (categorical)**
    - **Question:** Are there specific types of service providers considered?

row 18. **functional_status (categorical)**
    - **Question:** What are the possible functional statuses? What do 0 and 1 refer to?

**Comment by myesaya** [comment]
row 5. **committee_members (integer)**
•	**Question**: Is this number of year 2023?
•	**Ans**: This is the number of members in a water committee as of the year 2023 (count)

row 7. **annual_budget (integer)**
**Question**: Is the budget in Kwacha?
•	**Ans**: Yes, MWK

row 10. **tariff_costs_consider (categorical)**
•	**Question**: Can you specify this variable or list examples of costs considered?
•	**Ans**: Examples of costs considered before setting a water tariff were Affordability, Maintenance costs, Operation costs, Total replacement cost for the system, Set by local government, and Bill payments. 

row 13. **total_money (integer)**
  - **Question**: Is the budget in Kwacha?
-**Ans**: Yes MWK

row 15. **distance_materials (categorical)**
 -**Question**: How is "0-20 km" different from "within community"?
-**Ans**: Accessible within the community strictly meant within the community. 0-20km meant somewhere outside their village

row 16. **service_provider (categorical)**
- **Question**: Are there specific types of service providers considered?
-**Answer**: The possible answers to that question were Yes/No. Going further, no specific type of service provider was considered. 

row 18. **functional_status (categorical)**
- **Question**: What are the possible functional statuses? What do 0 and 1 refer to?
-**Ans**:  1=Functional, 0=Non functional

**Comment by mianzg** [comment]
@myesaya Thanks so much for your quick reply. Indeed, would you like to implement the changes by your self?

I prepare the following steps:

1. Go to https://github.com/openwashdata/boreholefuncmwi/blob/main/data-raw/dictionary.csv and Download the file.

<img width="1030" alt="download" src="https://github.com/openwashdata/boreholefuncmwi/assets/22420281/2f9933ed-6b37-4297-a554-14c12b8edcd3">

2. Open your downloaded `dictionary.csv` with Excel

3. Edit the column `description` for all the rows we discussed above, and SAVE it to csvfile 

4. Go to https://github.com/openwashdata/boreholefuncmwi/tree/main/data-raw and Select `Add File/Upload Files`

![github_add_file](https://github.com/openwashdata/boreholefuncmwi/assets/22420281/82215642-7370-4aa5-b294-f6edc2cf4fe1)

5. Upload 
    a. Upload the revised `dictionary.csv` file
    b. Write the commit message
    c. Select the option "Create a new branch", write the name as "dictionary" 
    d. Click the green button to Propose the change.

![upload](https://github.com/openwashdata/boreholefuncmwi/assets/22420281/c39d267a-b991-4680-91fe-d07e963774f6)

**Comment by myesaya** [comment]
![git](https://github.com/openwashdata/boreholefuncmwi/assets/105126009/9b958fa7-35db-4252-b993-3f176ec3b28c)
I can not load the revised file

**Comment by mianzg** [comment]
@myesaya Sorry for that. It was a mistake on my side. Could you try again?

**Comment by myesaya** [comment]
I have uploaded

**Comment by mianzg** [comment]
Thanks for the contribution! I reviewed it and merged it into the package.
