### ISSUE TITLE
Update data author and contributor information

### ISSUE THREAD

**Issue by mianzg** [openwashdata/boreholefuncmwi#2]
@myesaya Hi, the current data package include you and our package developer as the authors. 

Please provide all other data authors/contributors for this dataset if you are aware of with the format:

**First Name**:
**Family Name**:
**Email**:
**ORCiD (if available)**:

**Comment by myesaya** [comment]
**First Name**: Hastings
**Family Name:** Kayira
**Email**: hastingskayira95@gmail.com

**Comment by mianzg** [comment]
Great, thanks, I updated the author information.
