### ISSUE TITLE
Review data package before release

### ISSUE THREAD

**Issue by mianzg** [openwashdata/boreholefuncmwi#4]
Hi @larnsce this data package is ready to release on Zenodo. Please give a check if anything is missing.

I added a `.zenodo.json` file to following the instructions here: https://developers.zenodo.org/#add-metadata-to-your-github-repository-release This revises a few metadata fields that our workflow wants to change. I want to use this to test if it works.

**Comment by larnsce** [comment]
Thank you, @mianzg. I have reviewed it, and technical and documentation aspects look great. Thank you also for checking about the zenodo.json, that is something I had been wanting to explore a bit more. Did you generate this file automated from our CFF file?

I have one consideration about the author order. In a case like this, Mabvuto must remain the first author. He has shared this data, actively work on it during the course, and should also be the one that is contacted if people questions about it (maintainer). I realise that we don't have clear rules for this, which something that we need. But I would say that data we "find" out there and then re-publish, it's okay for one of us to be the first author. For data, directly coming from people that actively contribute to it, first author should remain there. Please discuss this with Juliette.

**Comment by mianzg** [comment]
I wrote the .zenodo.json file.

The order of authors are just based on the DESCRIPTION file. But I'm afraid that the maintainer role will always be at the first. I can revise the order and see how it looks.

**Comment by larnsce** [comment]
Exactly, you can change the order in the DESCRIPTION file and also make @myesaya the maintainer of the package.

**Comment by larnsce** [comment]
This could be interesting? 

https://github.com/pik-piam/citation/blob/master/R/cff2zenodo.R

Maybe to borrow from them and include a function in `washr`?

**Comment by mianzg** [comment]
Thanks for the review @larnsce. This package now is released on Zenodo @myesaya @J-preisig 👏🏼

**Comment by mianzg** [comment]
@myesaya Please select one of the data source category: academic, ngo, private, government, other
